### ISSUE TITLE
Add Automated Issue Assignment System via GitHub Actions

### ISSUE THREAD

**Issue by abeltavares** [ArvindParekh/Lofi-Music-App#20]
I propose adding an automated system to assign issues to contributors directly through GitHub comments. This feature would allow contributors to self-assign issues by commenting "take" on them, streamlining the process and reducing the conflicts people working on the same one.

The implementation would involve creating a `.github/workflows/issue-assign.yml` file that defines a GitHub Action. This action will listen for "take" comments on issues and use the GitHub API to assign the issue to the user who made the comment. The action will require minimal permissions to modify issue assignments and will operate under the security context provided by GitHub Actions.

After the implementation update the CONTRIBUTING.md to include guidelines on how contributors can use this feature.

**Comment by ArvindParekh** [comment]
I love the idea! 👍🏻 
Those wanting to work on an issue can get it assigned to them directly. I think a slash command (something like `/assign`) would be better.

Would you like to work on it @abeltavares?

**Comment by abeltavares** [comment]
> I love the idea! 👍🏻 Those wanting to work on an issue can get it assigned to them directly. I think a slash command (something like `/assign`) would be better.
> 
> Would you like to work on it @abeltavares?

` /assign` seems great.
Can work on it.
Please assign it to me.
