### ISSUE TITLE
[BUG] Scaling issue on Effect hover

### ISSUE THREAD

**Issue by ArvindParekh** [ArvindParekh/Lofi-Music-App#6]
Currently, when hovering over an effect, the image scales up as intended. However, this scaling behavior is not consistent across the entire container. Hovering over the text inside the container prematurely ends the scaling effect, resulting in an inconsistent user experience.

Preview: 

https://github.com/ArvindParekh/Lofi-Music-App/assets/71211731/65649c5c-9c43-4eda-aee5-62ef2b0c9503

To resolve this issue, we need to ensure that the scaling effect persists when hovering over the entire container, including the text. This may require a little play around with [Tailwind's Group Hover utility](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state).

**Comment by Sky-De** [comment]
@ArvindParekh assign this to me , thanks

**Comment by ArvindParekh** [comment]
Hi @Sky-De, thanks for showing interest! However, @GitGudCode440 has already raised a PR for it, so I'll be closing this issue for now. Do check out other issues if you'd like, or feel free to suggest bugs!
